
export const TableFields =  {
    LogEntry:{
        id:'',
        action_time:'',	
        object_id:'',	
        object_repr:'',	
        action_flag:'',	
        change_message:'',	
        content_type_id:'',	
        user_id:'',
    },
    Plans : {
    id:'',
    plan_id:'',
    plan_type:'',
    plan_details:'',
    plan_post_limit:'',
    plan_post_schedule:'',
    created_at:'',
    updated_at:'',
},
  MainData : {
    id:'',
    admin:'',
    session:'',
    user_active:'',
    plan_id:'',
    plan_status:'',
    plan_activate:'',
    plan_expiry:'',
    created_at:'',
    updated_at:'',
    objects:'',
    
},
  User : {
    id:'',
    email:'',
    name:'',
    password:'',
    last_login:'',
    profile_pic:'',
    created_at:'',
    updated_at:'',
    is_active:false,
    is_admin:true,
},
Group:{
    id:'',
    name:'',
},
  Permission : {
    id:'',
    name:'',
    content_type_id:0,
    codenane:'',
}, 
  ContentType : {
    id:'',
    app_label:'',
    model:'',
},
  Migrations : {
    id:'',
    app:'',
    name:'',
    applied:''
},
  Session : {
    session_key : '',
    session_data:'',
    expire_date:''
},
  FaceBookPage : {
    id:'',
    page_id:'',	
    page_extended_access_token:'',	
    page_extended_token_expiry:'',	
    page_profile_pic_url:'',	
    page_name:'',	
    fb_user_id_id:'',
},
  FaceBookUser : {
    id:'',	
    admin_id:'',
    user_access_token:'',	
    user_access_token_expiry:'',	
    user_extended_token:'',	
    user_extended_token_expiry:'',	
    user_token_status:'',	
    user_id:'',	
},
  Subscription : {
    id:'',	
    subscription_id:'',	
    plan_id:'',	
    customer_id:'',	
    status:'',	
    start_at:'',	
    end_at:'',	
    created_at:'',	
    updated_at:'',	
    user_id:'',	
},
  UserPlanDetails : {
    id:'',
    user:'',
    plan_type:'',	
    plan_status:'',	
    start_at:'',	
    end_at:'',	
    user_post_count:'',	
    user_post_schedule_count:'',	
    created_at:'',	
    updated_at:'',	
},

}

